name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Cypress Test
              uses: cypress-io/github-action@v6
              with: 
                start: 'npm run dev'
                build: 'npm run build'

            - name: Upload Cypress Artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: Cypress Result
                path: |
                    cypress/screenshots
                    cypress/videos
                    cypress/results
                if-no-files-found: ignore